# 窗口大小
_windowSize:
  width: 1000
  height: 600

# server
_server:
  port: 4242

# 生成py文件路径
_filepath: "log/gene.py"

# 模拟算法 默认DAG
_algo: "DAG"

# 网络连接配置，建议当端口被占用时修改
_connect:
  ip: '127.0.0.1'
  port: 8000
  connect_timeout: 1000  # 连接超时时间 ms
  max_attempts: 5        # 最大重连次数

# 开发环境dev，生产环境改为product
_env: "dev"

# 噪声环境
_simulation_env: false

# 错误率
_single_error_rate: 0.0012
_double_error_rate: 0.011
_measure_error_rate: 0.017